### ISSUE TITLE
SyntaxError: invalid syntax: return L @ x + d * x

### ISSUE THREAD

**Issue by abderhasan** [99991/matting#3]
Hello!

I'm running the code on a macOS, and always getting this error in alpha_matting.py (line 200): r`eturn L @ x + d * x`

`SyntaxError: invalid syntax
`

Do you have an idea on how I can fix this issue?

Thanks.

**Comment by 99991** [comment]
The `@`-operator is the [matrix multiplication operator](https://www.python.org/dev/peps/pep-0465/), available since 2014. I've replaced (hopefully) all occurrences of `@` with `.dot(...)`,  but there might be other issues with very old Python versions. Let me know if you should come across any problems!

**Comment by abderhasan** [comment]
Thanks so much for your kind reply and clarification, appreciate it!

**Comment by 99991** [comment]
Seems to be solved.
